/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  default?: boolean;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
    createdAt?: string;
  };
  stripeCustomerId?: string;
  clarkUserId?: string;
  customerNameAlt?: string;
  customerEmail?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    productId?: ProductReference;
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    street?: string;
    state?: string;
    zip?: string;
    country?: string;
    city?: string;
  };
  status?:
    | "pending"
    | "completed"
    | "cancelled"
    | "refunded"
    | "processing"
    | "shipped"
    | "delivered"
    | "returned"
    | "failed"
    | "on_hold"
    | "partially_refunded"
    | "awaiting_payment";
  orderDate?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  specifications?: Array<{
    key?: string;
    value?: string;
    _key: string;
  }>;
  description?: string;
  price?: number;
  productType?:
    | "gadget"
    | "accessory"
    | "home_appliance"
    | "electronics"
    | "footwear"
    | "clothing"
    | "books"
    | "toys"
    | "sports_equipment"
    | "beauty_products"
    | "health_products"
    | "automotive"
    | "other";
  image?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  category?: CategoryReference;
  brand?: BrandReference;
  releaseDate?: string;
  discount?: number;
  stock?: number;
  status?:
    | "sale_product"
    | "available"
    | "out_of_stock"
    | "pre_order"
    | "discontinued"
    | "limited_edition"
    | "hot_deal"
    | "best_seller"
    | "discontinued";
  rating?: number;
  reviews?: Array<{
    reviewer?: string;
    comment?: string;
    rating?: number;
    _key: string;
  }>;
  featured?: boolean;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  name?: string;
  slug?: Slug;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: string;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Address
  | ProductReference
  | Order
  | SanityImageAssetReference
  | CategoryReference
  | BrandReference
  | Product
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | AuthorReference
  | Post
  | BlockContent
  | Author
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/Queries/query.ts
// Variable: BRAND_QUERY
// Query: *[_type == 'brand'] | order(name asc){    _id,    name,    slug,    description,    logo}
export type BRAND_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: sanity/Queries/query.ts
// Variable: LATEST_BLOGS_QUERY
// Query: *[_type == 'post'] {  _id,  title,  slug,  publishedAt,  mainImage {    asset,    alt  },  categories[]-> {    _id,    title  },  author-> {    _id,    name,    slug,    image,    bio  },  body}
export type LATEST_BLOGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  body: BlockContent | null;
}>;

// Source: sanity/Queries/query.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == 'product'] | order(_createdAt desc){  _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug,  description,  price,  discount,  stock,  status,  rating,  productType,  featured,  releaseDate,  image[]{    asset,    hotspot  },  specifications[]{    key,    value  },  reviews[]{    reviewer,    comment,    rating  },  category->{    _id,    title,    slug  },  brand->{    _id,    name,    slug,    logo  }}
export type PRODUCT_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status:
    | "available"
    | "best_seller"
    | "discontinued"
    | "hot_deal"
    | "limited_edition"
    | "out_of_stock"
    | "pre_order"
    | "sale_product"
    | null;
  rating: number | null;
  productType:
    | "accessory"
    | "automotive"
    | "beauty_products"
    | "books"
    | "clothing"
    | "electronics"
    | "footwear"
    | "gadget"
    | "health_products"
    | "home_appliance"
    | "other"
    | "sports_equipment"
    | "toys"
    | null;
  featured: boolean | null;
  releaseDate: string | null;
  image: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  specifications: Array<{
    key: string | null;
    value: string | null;
  }> | null;
  reviews: Array<{
    reviewer: string | null;
    comment: string | null;
    rating: number | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  brand: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: sanity/Queries/query.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == 'product' && slug.current == $slug][0]{  _id,  name,  slug,  description,  price,  discount,  stock,  status,  rating,  productType,  featured,  releaseDate,  image[]{    asset,    hotspot  },  specifications[]{    key,    value  },  reviews[]{    reviewer,    comment,    rating  },  category->{    _id,    title,    slug  },  brand->{    _id,    name,    slug,    logo  }}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status:
    | "available"
    | "best_seller"
    | "discontinued"
    | "hot_deal"
    | "limited_edition"
    | "out_of_stock"
    | "pre_order"
    | "sale_product"
    | null;
  rating: number | null;
  productType:
    | "accessory"
    | "automotive"
    | "beauty_products"
    | "books"
    | "clothing"
    | "electronics"
    | "footwear"
    | "gadget"
    | "health_products"
    | "home_appliance"
    | "other"
    | "sports_equipment"
    | "toys"
    | null;
  featured: boolean | null;
  releaseDate: string | null;
  image: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  specifications: Array<{
    key: string | null;
    value: string | null;
  }> | null;
  reviews: Array<{
    reviewer: string | null;
    comment: string | null;
    rating: number | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  brand: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/Queries/query.ts
// Variable: FEATURED_PRODUCT_QUERY
// Query: *[_type == 'product' && featured == true] | order(_createdAt desc){  _id,  name,  slug,  price,  discount,  stock,  status,  rating,  productType,  featured,  image[]{    asset,    hotspot  },  category->{    _id,    title,    slug  },  brand->{    _id,    name,    slug  }}
export type FEATURED_PRODUCT_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status:
    | "available"
    | "best_seller"
    | "discontinued"
    | "hot_deal"
    | "limited_edition"
    | "out_of_stock"
    | "pre_order"
    | "sale_product"
    | null;
  rating: number | null;
  productType:
    | "accessory"
    | "automotive"
    | "beauty_products"
    | "books"
    | "clothing"
    | "electronics"
    | "footwear"
    | "gadget"
    | "health_products"
    | "home_appliance"
    | "other"
    | "sports_equipment"
    | "toys"
    | null;
  featured: true;
  image: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  brand: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: sanity/Queries/query.ts
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && category->slug.current == $slug] | order(_createdAt desc){  _id,  name,  slug,  price,  discount,  stock,  status,  rating,  productType,  featured,  image[]{    asset,    hotspot  },  category->{    _id,    title,    slug  },  brand->{    _id,    name,    slug  }}
export type PRODUCT_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status:
    | "available"
    | "best_seller"
    | "discontinued"
    | "hot_deal"
    | "limited_edition"
    | "out_of_stock"
    | "pre_order"
    | "sale_product"
    | null;
  rating: number | null;
  productType:
    | "accessory"
    | "automotive"
    | "beauty_products"
    | "books"
    | "clothing"
    | "electronics"
    | "footwear"
    | "gadget"
    | "health_products"
    | "home_appliance"
    | "other"
    | "sports_equipment"
    | "toys"
    | null;
  featured: boolean | null;
  image: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  brand: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: sanity/Queries/query.ts
// Variable: PRODUCT_BY_BRAND_QUERY
// Query: *[_type == 'product' && brand->slug.current == $slug] | order(_createdAt desc){  _id,  name,  slug,  price,  discount,  stock,  status,  rating,  productType,  featured,  image[]{    asset,    hotspot  },  category->{    _id,    title,    slug  },  brand->{    _id,    name,    slug  }}
export type PRODUCT_BY_BRAND_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status:
    | "available"
    | "best_seller"
    | "discontinued"
    | "hot_deal"
    | "limited_edition"
    | "out_of_stock"
    | "pre_order"
    | "sale_product"
    | null;
  rating: number | null;
  productType:
    | "accessory"
    | "automotive"
    | "beauty_products"
    | "books"
    | "clothing"
    | "electronics"
    | "footwear"
    | "gadget"
    | "health_products"
    | "home_appliance"
    | "other"
    | "sports_equipment"
    | "toys"
    | null;
  featured: boolean | null;
  image: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  brand: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'brand'] | order(name asc){\n    _id,\n    name,\n    slug,\n    description,\n    logo\n}": BRAND_QUERY_RESULT;
    "*[_type == 'post'] {\n  _id,\n  title,\n  slug,\n  publishedAt,\n  mainImage {\n    asset,\n    alt\n  },\n  categories[]-> {\n    _id,\n    title\n  },\n  author-> {\n    _id,\n    name,\n    slug,\n    image,\n    bio\n  },\n  body\n}": LATEST_BLOGS_QUERY_RESULT;
    "*[_type == 'product'] | order(_createdAt desc){\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug,\n  description,\n  price,\n  discount,\n  stock,\n  status,\n  rating,\n  productType,\n  featured,\n  releaseDate,\n  image[]{\n    asset,\n    hotspot\n  },\n  specifications[]{\n    key,\n    value\n  },\n  reviews[]{\n    reviewer,\n    comment,\n    rating\n  },\n  category->{\n    _id,\n    title,\n    slug\n  },\n  brand->{\n    _id,\n    name,\n    slug,\n    logo\n  }\n}": PRODUCT_QUERY_RESULT;
    "*[_type == 'product' && slug.current == $slug][0]{\n  _id,\n  name,\n  slug,\n  description,\n  price,\n  discount,\n  stock,\n  status,\n  rating,\n  productType,\n  featured,\n  releaseDate,\n  image[]{\n    asset,\n    hotspot\n  },\n  specifications[]{\n    key,\n    value\n  },\n  reviews[]{\n    reviewer,\n    comment,\n    rating\n  },\n  category->{\n    _id,\n    title,\n    slug\n  },\n  brand->{\n    _id,\n    name,\n    slug,\n    logo\n  }\n}": PRODUCT_BY_SLUG_QUERY_RESULT;
    "*[_type == 'product' && featured == true] | order(_createdAt desc){\n  _id,\n  name,\n  slug,\n  price,\n  discount,\n  stock,\n  status,\n  rating,\n  productType,\n  featured,\n  image[]{\n    asset,\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    slug\n  },\n  brand->{\n    _id,\n    name,\n    slug\n  }\n}": FEATURED_PRODUCT_QUERY_RESULT;
    "*[_type == 'product' && category->slug.current == $slug] | order(_createdAt desc){\n  _id,\n  name,\n  slug,\n  price,\n  discount,\n  stock,\n  status,\n  rating,\n  productType,\n  featured,\n  image[]{\n    asset,\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    slug\n  },\n  brand->{\n    _id,\n    name,\n    slug\n  }\n}": PRODUCT_BY_CATEGORY_QUERY_RESULT;
    "*[_type == 'product' && brand->slug.current == $slug] | order(_createdAt desc){\n  _id,\n  name,\n  slug,\n  price,\n  discount,\n  stock,\n  status,\n  rating,\n  productType,\n  featured,\n  image[]{\n    asset,\n    hotspot\n  },\n  category->{\n    _id,\n    title,\n    slug\n  },\n  brand->{\n    _id,\n    name,\n    slug\n  }\n}": PRODUCT_BY_BRAND_QUERY_RESULT;
  }
}
