'use client'
import React from 'react'

const ShopPage = () => {
  return (
    <div className='flex flex-2 gap-2'>
    <div className='bg-green-500 border-2 border-blue-800 p-1 text-justify rounded-2xl'>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, porro nihil ipsam provident eaque dicta dolores blanditiis delectus fugit, saepe eveniet soluta consectetur officia. Ratione, fugit? Ipsa enim, obcaecati laboriosam labore repellat sapiente sunt voluptatem minus delectus reiciendis cupiditate, quis aperiam nemo molestiae commodi itaque. Autem in ut impedit eos! Incidunt, soluta id voluptates consequuntur placeat fugit dicta error quos iusto est numquam vitae rerum ipsum? Qui nam maxime quia aliquid corporis est accusantium natus impedit porro voluptatibus quas laborum laboriosam nostrum minus nihil blanditiis alias doloribus praesentium veniam, saepe fugiat. Harum culpa facilis quia, aliquam distinctio iure at cum! Excepturi dolores maxime aut labore praesentium explicabo quisquam consequatur eaque voluptate pariatur soluta incidunt ullam qui sint veniam sequi, culpa commodi odit provident numquam fugit porro. Quisquam unde natus odio aut aliquam? Qui sed consequatur illum, culpa, cupiditate accusantium repellendus ipsam illo placeat enim assumenda error dolore quia laudantium ullam nobis rerum corrupti aspernatur cum modi vel soluta recusandae? Enim cupiditate debitis a nostrum vitae sint qui nesciunt. Ratione facilis, explicabo ipsam vero deleniti tempora earum, quo ad perferendis aperiam non minima consequuntur vitae reiciendis accusamus repudiandae totam autem numquam labore beatae ipsum nostrum mollitia? Eos odit magni nulla rerum necessitatibus, hic temporibus officia. Repellat eum corrupti nulla nesciunt ratione earum hic, eveniet velit! Incidunt animi cum beatae, sed eos ipsa nihil. Qui cupiditate dolorum maxime quae non molestiae? Molestias ad architecto quae obcaecati delectus iste error alias at cupiditate.
    </div>

    <div>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, porro nihil ipsam provident eaque dicta dolores blanditiis delectus fugit, saepe eveniet soluta consectetur officia. Ratione, fugit? Ipsa enim, obcaecati laboriosam labore repellat sapiente sunt voluptatem minus delectus reiciendis cupiditate, quis aperiam nemo molestiae commodi itaque. Autem in ut impedit eos! Incidunt, soluta id voluptates consequuntur placeat fugit dicta error quos iusto est numquam vitae rerum ipsum? Qui nam maxime quia aliquid corporis est accusantium natus impedit porro voluptatibus quas laborum laboriosam nostrum minus nihil blanditiis alias doloribus praesentium veniam, saepe fugiat. Harum culpa facilis quia, aliquam distinctio iure at cum! Excepturi dolores maxime aut labore praesentium explicabo quisquam consequatur eaque voluptate pariatur soluta incidunt ullam qui sint veniam sequi, culpa commodi odit provident numquam fugit porro. Quisquam unde natus odio aut aliquam? Qui sed consequatur illum, culpa, cupiditate accusantium repellendus ipsam illo placeat enim assumenda error dolore quia laudantium ullam nobis rerum corrupti aspernatur cum modi vel soluta recusandae? Enim cupiditate debitis a nostrum vitae sint qui nesciunt. Ratione facilis, explicabo ipsam vero deleniti tempora earum, quo ad perferendis aperiam non minima consequuntur vitae reiciendis accusamus repudiandae totam autem numquam labore beatae ipsum nostrum mollitia? Eos odit magni nulla rerum necessitatibus, hic temporibus officia. Repellat eum corrupti nulla nesciunt ratione earum hic, eveniet velit! Incidunt animi cum beatae, sed eos ipsa nihil. Qui cupiditate dolorum maxime quae non molestiae? Molestias ad architecto quae obcaecati delectus iste error alias at cupiditate.
    </div>
    <div>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque, porro nihil ipsam provident eaque dicta dolores blanditiis delectus fugit, saepe eveniet soluta consectetur officia. Ratione, fugit? Ipsa enim, obcaecati laboriosam labore repellat sapiente sunt voluptatem minus delectus reiciendis cupiditate, quis aperiam nemo molestiae commodi itaque. Autem in ut impedit eos! Incidunt, soluta id voluptates consequuntur placeat fugit dicta error quos iusto est numquam vitae rerum ipsum? Qui nam maxime quia aliquid corporis est accusantium natus impedit porro voluptatibus quas laborum laboriosam nostrum minus nihil blanditiis alias doloribus praesentium veniam, saepe fugiat. Harum culpa facilis quia, aliquam distinctio iure at cum! Excepturi dolores maxime aut labore praesentium explicabo quisquam consequatur eaque voluptate pariatur soluta incidunt ullam qui sint veniam sequi, culpa commodi odit provident numquam fugit porro. Quisquam unde natus odio aut aliquam? Qui sed consequatur illum, culpa, cupiditate accusantium repellendus ipsam illo placeat enim assumenda error dolore quia laudantium ullam nobis rerum corrupti aspernatur cum modi vel soluta recusandae? Enim cupiditate debitis a nostrum vitae sint qui nesciunt. Ratione facilis, explicabo ipsam vero deleniti tempora earum, quo ad perferendis aperiam non minima consequuntur vitae reiciendis accusamus repudiandae totam autem numquam labore beatae ipsum nostrum mollitia? Eos odit magni nulla rerum necessitatibus, hic temporibus officia. Repellat eum corrupti nulla nesciunt ratione earum hic, eveniet velit! Incidunt animi cum beatae, sed eos ipsa nihil. Qui cupiditate dolorum maxime quae non molestiae? Molestias ad architecto quae obcaecati delectus iste error alias at cupiditate.
    </div>
    </div>
  )
}

export default ShopPage;
